/* (c) https://github.com/MontiCore/monticore */
package montiarc._symboltable;

import de.monticore.expressions.expressionsbasis._ast.ASTExpression;
import de.monticore.symbols.compsymbols._symboltable.CompSymbolsSymbols2Json;
import de.monticore.symbols.compsymbols._symboltable.ComponentTypeSymbol;
import de.monticore.symbols.compsymbols._symboltable.ComponentTypeSymbolDeSer;
import de.monticore.symboltable.serialization.json.JsonObject;
import montiarc.MontiArcMill;
import org.codehaus.commons.nullanalysis.NotNull;
import variablearc._symboltable.IVariableArcComponentTypeSymbol;
import variablearc._symboltable.IVariableArcComponentTypeSymbolDeSer;
import variablearc._symboltable.VariableArcVariationPointDeSer;
import variablearc.evaluation.ExpressionSetDeSer;

import java.io.IOException;
import java.util.Optional;

public class MontiArcComponentTypeSymbolDeSer extends ComponentTypeSymbolDeSer
  implements IVariableArcComponentTypeSymbolDeSer {

  protected final ExpressionSetDeSer expressionSetDeSer;
  protected final VariableArcVariationPointDeSer variationPointDeSer;

  public MontiArcComponentTypeSymbolDeSer() {
    expressionSetDeSer = new ExpressionSetDeSer(this::parse);
    variationPointDeSer = new VariableArcVariationPointDeSer(this::parse);
  }

  protected Optional<ASTExpression> parse(String e) {
    try {
      return MontiArcMill.parser().parse_StringExpression(e);
    } catch (IOException ex) {
      return Optional.empty();
    }
  }

  @Override
  public String serialize(ComponentTypeSymbol toSerialize, CompSymbolsSymbols2Json s2j) {
    /* generated by template _symboltable.serialization.symbolDeSer.Serialize4SymbolDeSer*/

    de.monticore.symboltable.serialization.JsonPrinter p = s2j.getJsonPrinter();
    p.beginObject();
    p.member(de.monticore.symboltable.serialization.JsonDeSers.KIND, getSerializedKind());
    p.member(de.monticore.symboltable.serialization.JsonDeSers.NAME, toSerialize.getName());
    p.member(de.monticore.symboltable.serialization.JsonDeSers.FULL_NAME, toSerialize.getFullName());
    p.member(de.monticore.symboltable.serialization.JsonDeSers.PACKAGE_NAME, toSerialize.getPackageName());

    // serialize symbolrule attributes
    serializeNumOptParams(toSerialize.getNumOptParams(), s2j);
    serializeSuperComponents(toSerialize.getSuperComponentsList(), s2j);
    serializeRefinements(toSerialize.getRefinementsList(), s2j);
    serializeParameter(toSerialize.getParameterList(), s2j);

    // ---- Start Override
    // Variable symbols need to be serialized before the spanned scope
    if (toSerialize instanceof IVariableArcComponentTypeSymbol) {
      serializeConstraints((IVariableArcComponentTypeSymbol) toSerialize, s2j);
      serializeVariationPoint((IVariableArcComponentTypeSymbol) toSerialize, s2j);
    }
    // ---- End Override

    // serialize spanned scope
    if (toSerialize.getSpannedScope().isExportingSymbols()
      && toSerialize.getSpannedScope().getSymbolsSize() > 0) {
      toSerialize.getSpannedScope().accept(s2j.getTraverser());
    }
    s2j.getTraverser().addTraversedElement(toSerialize.getSpannedScope());

    serializeAddons(toSerialize, s2j);
    p.endObject();

    return p.toString();
  }

  @Override
  protected void deserializeAddons(@NotNull ComponentTypeSymbol component, @NotNull JsonObject json) {
    super.deserializeAddons(component, json);
    if (component instanceof IVariableArcComponentTypeSymbol) {
      deserializeConstraints((IVariableArcComponentTypeSymbol) component, json);
      deserializeVariationPoints((IVariableArcComponentTypeSymbol) component, json);
    }
  }

  @Override
  public ExpressionSetDeSer getExpressionSetDeSer() {
    return expressionSetDeSer;
  }

  @Override
  public VariableArcVariationPointDeSer getVariationPointDeSer() {
    return variationPointDeSer;
  }
}
