/* (c) https://github.com/MontiCore/monticore */
package montiarc.generator.codegen;

import arcbasis._symboltable.ArcComponentTypeSymbol;
import com.google.common.base.Preconditions;
import de.monticore.expressions.assignmentexpressions._ast.ASTAssignmentExpression;
import de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions;
import de.monticore.expressions.assignmentexpressions._prettyprint.AssignmentExpressionsPrettyPrinter;
import de.monticore.expressions.expressionsbasis._ast.ASTNameExpression;
import de.monticore.prettyprint.IndentPrinter;
import de.monticore.symbols.compsymbols._symboltable.PortSymbol;
import de.monticore.symboltable.ISymbol;
import de.monticore.types.check.SymTypeExpression;
import de.monticore.types3.SymTypeRelations;
import de.monticore.types3.TypeCheck3;
import montiarc._symboltable.IMontiArcScope;
import montiarc.check.MontiArcTypeCheck;
import org.codehaus.commons.nullanalysis.NotNull;
import org.codehaus.commons.nullanalysis.Nullable;
import variablearc._symboltable.VariantPortSymbol;

import java.util.List;
import java.util.Optional;

public class AssignmentExpressionsMA2JSimPrinter extends AssignmentExpressionsPrettyPrinter {

  protected ArcComponentTypeSymbol currentVariant;

  public AssignmentExpressionsMA2JSimPrinter(@NotNull IndentPrinter printer, boolean printComments, @Nullable ArcComponentTypeSymbol currentVariant) {
    super(Preconditions.checkNotNull(printer), printComments);
    this.currentVariant = currentVariant;
  }

  @Override
  public void handle(ASTAssignmentExpression expr) {
    Preconditions.checkState(expr.getLeft().getEnclosingScope() != null);
    Preconditions.checkState(expr.getLeft().getEnclosingScope() instanceof IMontiArcScope);

    if (this.isPrintComments()) {
      de.monticore.prettyprint.CommentPrettyPrinter.printPreComments(expr, getPrinter());
    }

    /* generated by template _prettyprinter.pp.Block*/
    if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.EQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PLUSEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.MINUSEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.STAREQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.SLASHEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.AND_EQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PIPEEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.ROOFEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.GTGTEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.GTGTGTEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.LTLTEQUALS || expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PERCENTEQUALS) { // opt: 0 req: 2
      expr.getLeft().accept(getTraverser());

      if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.LTLTEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("<<=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PIPEEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("|=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PLUSEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("+=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.SLASHEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("/=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.MINUSEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("-=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.STAREQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("*=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.GTGTGTEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print(">>>=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.EQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.GTGTEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print(">>=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.AND_EQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("&=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.ROOFEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("^=");
      } else if (expr.getOperator() == de.monticore.expressions.assignmentexpressions._ast.ASTConstantsAssignmentExpressions.PERCENTEQUALS) {
        /* generated by template _prettyprinter.pp.Terminal*/
        getPrinter().stripTrailing();
        getPrinter().print("%=");
      }
      if (currentVariant != null) MontiArcTypeCheck.enterContext(currentVariant);
      SymTypeExpression typeOfLeft = TypeCheck3.typeOf(expr.getLeft());
      if (currentVariant != null) MontiArcTypeCheck.leaveContext();
      if (!typeOfLeft.isPrimitive() && SymTypeRelations.unbox(typeOfLeft).isPrimitive()) {
        this.getPrinter().print("(" + SymTypeRelations.unbox(typeOfLeft).asPrimitive().getPrimitiveName() + ")");
      }
      expr.getRight().accept(getTraverser());
    }


    if (this.isPrintComments()) {
      de.monticore.prettyprint.CommentPrettyPrinter.printPostComments(expr, getPrinter());
    }

    if (expr.getOperator() == ASTConstantsAssignmentExpressions.EQUALS
      && expr.getLeft() instanceof ASTNameExpression) {

      ASTNameExpression left = (ASTNameExpression) expr.getLeft();
      String name = left.getName();
      // Optional<ISymbol> optSym = left.getDefiningSymbol(); // Not available yet

      Optional<PortSymbol> port = Optional.ofNullable(currentVariant).flatMap(v -> v.getPort(name, true)).or(() -> ((IMontiArcScope) left.getEnclosingScope()).resolvePortMany(name).stream().findAny());

      if (port.isPresent()) {

        this.getPrinter().println(";");
        if (!port.get().getType().isPrimitive()) {
          this.getPrinter().print(String.format("if (%s != null) ", name));
        }
        // calc variant suffix
        if (port.get() instanceof VariantPortSymbol) {
          port = port.map(p -> ((VariantPortSymbol) p).getOriginal());
        }
        List<PortSymbol> ports = ISymbol.sortSymbolsByPosition(port.get().getEnclosingScope().resolvePortMany(name));
        String suffix = ports.size() <= 1 ? "" : Integer.toString(ports.indexOf(port.get()));

        this.getPrinter().print(String.format("context.port_%s().send(%s);", name + suffix, name));
      }
    }
  }
}
