# (c) https://github.com/MontiCore/monticore  
# Build JAVA applications using Gradle (https://gradle.org/)

# Set up environment variables and configurations to be executed before each job
before_script:
  # Set Gradle user home to the current directory's .gradle folder
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Store the local Gradle build cache
.cache_gradle_pull_push: &cache_gradle_pull_push
  cache:
    key: gradle-$CI_COMMIT_REF_SLUG
    fallback_keys:
      - gradle-$CI_DEFAULT_BRANCH
      - gradle-fallback
    paths:
      - .gradle/caches/
    policy: pull-push

.cache_gradle_pull_only: &cache_gradle_pull_only
  cache:
    key: gradle-$CI_COMMIT_REF_SLUG
    fallback_keys:
      - gradle-$CI_DEFAULT_BRANCH
      - gradle-fallback
    paths:
      - .gradle/caches/
    policy: pull-push

stages:
  - build
  - test
  - check
  - deploy
  - downstream
  - mirror

Build:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  <<: *cache_gradle_pull_push
  stage: build
  allow_failure: false
  script:
    - gradle clean assemble --stacktrace --build-cache --configuration-cache -PenableLanguageServer -Pde.monticore.gradle.performance_statistic="false" --refresh-dependencies

Unit Test:
  stage: test
  <<: *cache_gradle_pull_push
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  allow_failure: false
  script:
    - gradle test jacocoAggregatedTestReport --stacktrace --build-cache --configuration-cache -PenableLanguageServer -Pde.monticore.gradle.performance_statistic="false"
    - awk -F","
      '{ instructions += $4 + $5; covered += $5 } END
      { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }'
      'build/reports/test-coverage/jacocoAggregated.csv'
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reports/test-coverage/jacocoAggregated.xml
      junit: ./**/test-results/test/**/TEST-*.xml
    paths:
      - ./**/build/**/reports/test-coverage/jacoco.xml
    when: always

Test Templates:
  stage: test
  <<: *cache_gradle_pull_push
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  needs: ["Build"]
  allow_failure: false
  script:
    - gradle publishToMavenLocal :gradle-plugins:publishAllToMavenLocal --stacktrace --build-cache --configuration-cache -PenableLanguageServer -Pde.monticore.gradle.performance_statistic="false" --refresh-dependencies
    - |
      for template_dir in templates/*/; do
        gradle -I ../test-templates.init.gradle -p "$template_dir" build --stacktrace
      done

Deploy Nexus:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  <<: *cache_gradle_pull_only
  stage: deploy
  script:
    - gradle publish :gradle-plugins:publishAll -PmavenPassword=$pass -PmavenUser=$user --build-cache --configuration-cache -PenableLanguageServer -Pde.monticore.gradle.performance_statistic="false"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

Trigger Digital Twin:
  stage: downstream
  needs:
    - job: "Deploy Nexus"
      optional: true
  allow_failure: false
  trigger:
    project: monticore/umlp-anwendungen/digital-twin
    branch: main
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

# Mirrors this repository to GitHub.
#
# The mirror will always be at either HEAD or HEAD+1 (depending on whether cleanup is necessary).
# For more information, visit: https://git.rwth-aachen.de/monticore/auxiliary-development-tools/github-mirror-tools (Available internally only)
Github Mirror:
  stage: mirror
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  variables:
    # The repository is edited during this job. To make sure that no changes persist, we instruct GitLab to always
    # create a fresh clone of the repository instead of caching it and attempting to remove any changes.
    #
    # See https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
    GIT_STRATEGY: clone
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SE_CIBUILD_SSH_PRIV_KEY_4MA")
    - echo "$SE_CIBUILD_SSH_PRIV_KEY_4MA" | tr -d '\r' | ssh-add -
    - git config --global user.email "noreply-ci@se-rwth.de"
    - git config --global user.name "MontiCore Mirroring Bot"
    - git checkout "$CI_COMMIT_REF_NAME" # GitLab checks out a commit in detached HEAD mode by default, but we want to commit to the branch and push.
    - mkdir -p ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - git lfs fetch --all
    - git remote add github git@github.com:MontiCore/montiarc.git
    - git fetch --all
    - if git rev-parse --quiet --verify github/dev > /develop/null;
      then git pull --rebase github dev;
      fi
    - git push --force github develop:dev
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

Verify Formatting:
  stage: check
  needs: []
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  allow_failure: false
  script:
    - gradle spotlessCheck

Check Dependency Updates:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:8.14.4-jdk21
  stage: check
  needs: []
  allow_failure: true
  script:
    - gradle dependencyUpdates -PenableLanguageServer
    - |
      echo "Checking for outdated dependencies..."
      REPORT_FILE="build/versions/dependency-updates.json"
      if [ ! -f "$REPORT_FILE" ]; then
        echo "Report not found: $REPORT_FILE"
        exit 1
      fi
      
      OUTDATED_BLOCK=$(sed -n '/"outdated": {/,/}/p' build/versions/dependency-updates.json)
      OUTDATED_COUNT=$(echo "$OUTDATED_BLOCK" | grep -oP '"count":\s*\K\d+' | head -1)
      if [ "$OUTDATED_COUNT" -gt 4 ]; then
        echo "Found $OUTDATED_COUNT outdated dependencies."
        exit 1
      else
        echo "All dependencies are up to date."
      fi
  artifacts:
    paths:
      - build/versions/dependency-updates.json
    when: always

Check Links:
  # We need a JDK 17+ image for this job since the link checker requires Java 17.
  image: eclipse-temurin:17-jdk-alpine
  stage: check
  # We don't want to fail the pipeline if a link is invalid. Therefore, allow
  # failure regardless of whether the tool exists with an error code.
  allow_failure: true
  before_script:
    - 'apk --no-cache add curl'
  script:
    - 'curl --location --header "PRIVATE-TOKEN: $secibuildinfstrtoken" "https://git.rwth-aachen.de/api/v4/projects/se%2Finfrastructure%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build" --output MDLinkChecker.jar'
    - 'java -jar MDLinkChecker.jar -t "$secibuildtoken" -r . -p'
  # The link-check does not depend on any artifacts generated by other jobs and
  # can therefore run immediately.
  needs: []
  rules:
    - when: never # Disabled until the link-checker jar is fixed
