# (c) https://github.com/MontiCore/monticore  
# Build JAVA applications using Apache Maven (http://maven.apache.org)

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3.5.4-jdk-8-alpine

cache:
  paths:
    - .m2/repository/
  key: "$CI_COMMIT_SHA" # Cache across branch and stage

stages:
  - build
  - test
  - post-test
  - check

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"


# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
Validate Maven:
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile package -DskipTests
  artifacts:
    paths:
      - applications/bumperbot/target/
      - generators/cd2pojo/target/
      - generators/maa2java-xtend/target/
      - languages/arc-fe/target/
      - languages/montiarc-fe/target/
      - libraries/lejos-rte/target/
      - libraries/maJavaLib/target/
      - libraries/maa-rte/target/
      - libraries/simulator-rte/target/
      
Validate Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.7-jdk8
  stage: build
  allow_failure: false
  artifacts:
    paths:
      - applications/bumperbot/target/
      - generators/cd2pojo/target/
      - generators/maa2java-xtend/target/
      - languages/arc-fe/target/
      - languages/montiarc-fe/target/
      - libraries/lejos-rte/target/
      - libraries/maJavaLib/target/
      - libraries/maa-rte/target/
      - libraries/simulator-rte/target/
  script:
    - gradle clean assemble
    
Unit Test Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.7-jdk8
  stage: test
  allow_failure: false
  dependencies: 
    - Validate Gradle #download artifacts from build
  needs: ["Validate Gradle"]
  script:
    - gradle test

# Run Unit Tests after build
.unit_test_template: &unit_test_definition
  stage: test
  coverage: '/\d+.\d+ \% covered/'
  script:
    - mvn $MAVEN_CLI_OPTS test package
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",  instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' ./languages/arc-fe/target/site/jacoco/jacoco.csv
  dependencies:
    - Validate Maven #download artifacts from build
  artifacts:
    reports:
      junit:
        - ./generators/maa2java-xtend/target/surefire-reports/TEST-*.xml
        - ./libraries/simulator-rte/target/surefire-reports/TEST-*.xml
        - ./languages/montiarc-fe/target/surefire-reports/TEST-*.xml

Unit Test JDK 8:
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8
  <<: *unit_test_definition

Unit Test JDK 14:
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-14
  # We do not require JDK 14 support yet. We appreciate it though.
  allow_failure: true
  <<: *unit_test_definition

Unit Test Amazon Corretto JDK 8:
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-amazoncorretto-8
  # We do not require Amazon Corretto JDK 11 support. We appreciate it though.
  allow_failure: true
  <<: *unit_test_definition

Deploy Nexus:
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8
  stage: post-test
  script:
    - mvn -U $MAVEN_CLI_OPTS clean deploy
  only:
    - develop

Code Quality:
  stage: post-test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  cache: {}
  tags:
    - shell
    - docker
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    # Update Codeclimate and SonarJava Plugin
    - docker run  --rm
      --env CODECLIMATE_CODE="$PWD"
      --env CONTAINER_TIMEOUT_SECONDS=150000
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate engines:install
    # Check Code Quality
    - docker run --rm
      --env CODECLIMATE_CODE="$PWD"
      --env CONTAINER_TIMEOUT_SECONDS=150000
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate analyze -f json > codeclimate.json
    #"registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: codeclimate.json

checkMDLinks:
  stage: check
  dependencies:
    - Code Quality
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/montiarc/core/-/tree/develop"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"
  only:
    - develop
