# Build JAVA applications using Apache Maven (http://maven.apache.org)

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository/
    - applications/bumperbot/target/
    - generators/cd2pojo/target/
    - generators/maa2java/target/
    - languages/montiarc-fe/target/
    - libraries/lejos-rte/target/
    - libraries/maJavaLib/target/
    - libraries/maa-rte/target/
    - libraries/simulator-rte/target/
  key: "$CI_COMMIT_SHA" # Cache across branch and stage

stages:
  - build
  - test
  - quality-report

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"


# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
validate:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile package -DskipTests=true

# Run Unit Tests after build
unit test:
  image: maven:3-jdk-8
  stage: test
  coverage: '/\d+.\d+ \% covered/'
  script:
    - mvn $MAVEN_CLI_OPTS test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' ./languages/montiarc-fe/target/site/jacoco/jacoco.csv
  except:
    - master
  artifacts:
    reports:
      junit:
      - ./generators/maa2java/target/surefire-reports/TEST-*.xml
      - ./libraries/simulator-rte/target/surefire-reports/TEST-*.xml
      - ./languages/montiarc-fe/target/surefire-reports/TEST-*.xml
      
code_quality:
  stage: quality-report
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  tags:
    - shell
    - docker
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    # Update Codeclimate and SonarJava Plugin
    - docker run  --rm 
      --env CODECLIMATE_CODE="$PWD" 
      --env CONTAINER_TIMEOUT_SECONDS=150000 
      --volume "$PWD":/code 
      --volume /var/run/docker.sock:/var/run/docker.sock 
      --volume /tmp/cc:/tmp/cc 
      codeclimate/codeclimate engines:install
    # Check Code Quality
    - docker run --rm 
       --env CODECLIMATE_CODE="$PWD" 
       --env CONTAINER_TIMEOUT_SECONDS=150000 
       --volume "$PWD":/code 
       --volume /var/run/docker.sock:/var/run/docker.sock 
       --volume /tmp/cc:/tmp/cc 
       codeclimate/codeclimate analyze -f json > codeclimate.json
        #"registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: codeclimate.json
