# (c) https://github.com/MontiCore/monticore  
# Build JAVA applications using Apache Maven (http://maven.apache.org)

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository/
  key: "$CI_COMMIT_SHA" # Cache across branch and stage

stages:
  - build
  - test
  - post-test
  - check
  - mirror
      
Validate Gradle:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8
  stage: build
  allow_failure: false
  artifacts:
    paths:
      - applications/bumperbot/target/
      - applications/factory/target/
      - applications/factoryTask/target/
      - applications/lightControl/target/
      - generators/cd2pojo/target/
      - generators/ma2java/target/
      - languages/arc-fe/target/
      - languages/behavior-fe/target/
      - languages/montiarc-fe/target/
      - libraries/lejos-rte/target/
      - libraries/majava-rte/target/
      - libraries/simulator-rte/target/
    expire_in: 1 week
  script:
    - gradle clean assemble
    
.unit_test_template: &unit_test_definition
  stage: test
  dependencies: 
    - Validate Gradle #download artifacts from build
  needs: ["Validate Gradle"]
  script:
    - gradle test aggregatedJacocoReport
  artifacts:
    paths:
      - target/reports/jacoco/aggregatedJacocoReport/aggregatedJacocoReport.xml
      - target/reports/jacoco/aggregatedJacocoReport/aggregatedJacocoReport.csv
    expire_in: 1 week

Unit Test JDK 8:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8
  allow_failure: false
  <<: *unit_test_definition

Unit Test JDK 11:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk11
  allow_failure: false
  <<: *unit_test_definition

Deploy Nexus:
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8
  stage: post-test
  script:
    - gradle publish -PmavenPassword=$pass -PmavenUser=$user
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

# Gitlab can visualize cobertura code coverage reports, but we have jacoco reports.
# Thus, we will convert our jacoco report to a cobertura report:
# Moreover we will print jacoco's instruction coverage to the command line so that gitlab parses it and creates a
# coverage badge for us.
Code Coverage:
  stage: post-test
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - awk -F "," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",  instructions, "instructions covered"; print "Total " 100*covered/instructions, "% covered" }' target/reports/jacoco/aggregatedJacocoReport/aggregatedJacocoReport.csv
    - python /opt/cover2cover.py target/reports/jacoco/aggregatedJacocoReport/aggregatedJacocoReport.xml languages/arc-fe/src/main/java/ applications/bumperbot/src/main/java/ applications/factory/src/main/java/ applications/factoryTask/src/main/java/ generators/cd2pojo/src/main/java/ generators/ma2java/src/main/java/ languages/arc-fe/src/main/java/ languages/behavior-fe/src/main/java/ languages/montiarc-fe/src/main/java/ libraries/lejos-rte/src/main/java/ libraries/majava-rte/src/main/java/ libraries/simulator-rte/src/main/java/ > cobertura.xml
  needs: ["Unit Test JDK 8"]
  dependencies:
    - Unit Test JDK 8
  artifacts:
    reports:
      cobertura: cobertura.xml
    expire_in: 1 week

checkMDLinks:
  stage: check
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3.5.4-jdk-8-alpine
  dependencies:
    - Code Coverage
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fauxiliary-development-tools%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/montiarc/core/-/tree/develop"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"

# Mirrors this repository to GitHub.
#
# The mirror will always be at either HEAD or HEAD+1 (depending on whether cleanup is necessary).
# For more information, visit: https://git.rwth-aachen.de/monticore/auxiliary-development-tools/github-mirror-tools (Available internally only)
Github Mirror:
  stage: mirror
  image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8
  variables:
    # The repository is edited during this job. To make sure that no changes persist, we instruct GitLab to always
    # create a fresh clone of the repository instead of caching it and attempting to remove any changes.
    #
    # See https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
    GIT_STRATEGY: clone
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SE_CIBUILD_SSH_PRIV_KEY")
    - echo "$SE_CIBUILD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email "noreply-ci@se-rwth.de"
    - git config --global user.name "MontiCore Mirroring Bot"
    - git checkout "$CI_COMMIT_REF_NAME" # GitLab checks out a commit in detached HEAD mode by default, but we want to commit to the branch and push.
    - mkdir -p ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - git lfs fetch --all
    - git remote add github git@github.com:MontiCore/montiarc.git
    - git fetch --all
    - if git rev-parse --quiet --verify github/"$CI_COMMIT_BRANCH" > /dev/null; 
      then git pull --rebase github "$CI_COMMIT_BRANCH";
      fi
    - git push --force github $CI_COMMIT_BRANCH
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
