site_name: MontiArc
theme:
  name: 'material'
  favicon: 'docs/img/favicon.png'
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - toc.follow
    - content.tabs.link
    - social
  logo: img/icon.png
  favicon: img/icon.png

site_url: https://monticore.github.io/montiarc/
repo_url: https://github.com/MontiCore/montiarc/
edit_uri: ""

copyright: '(c) https://github.com/MontiCore/monticore'

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MontiCore/montiarc
    - icon: fontawesome/solid/paper-plane
      link: mailto:webmaster@se-rwth.de

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: 'index.md'
  - Beginners Guide: 'BeginnersGuide.md'
  - Usage:
      - Getting Started: 'usage/GettingStarted.md'
      - CD2Java CL Tool: 'usage/CD2PojoCLTool.md'
      - CD2Java Gradle Plugin: 'usage/CD2PojoGradlePlugin.md'
      - MontiArc CL Tool: 'usage/MontiArcCLTool.md'
      - MontiArc Gradle Plugin: 'usage/MontiArcGradlePlugin.md'
  - Component: 
      - Overview: 'Component.md'
      - Decomposition: 'component/Decomposition.md'
      - Generics: 'component/Generics.md'
      - Inheritance: 'component/Inheritance.md'
      - Interfaces: 'component/Interfaces.md'
      - Parameters: 'component/Parameter.md'
      - Testing: 'component/Testing.md'
  - Behavior: 
      - Overview: 'Behavior.md'
      - Automata: 'behavior/Automata.md'
      - Compute: 'behavior/Compute.md'
      - Expressions: 'behavior/Expressions.md'
      - Statements: 'behavior/Statements.md'
      - Variables: 'behavior/Variables.md'
  - TypeSystem: 
      - Overview: 'TypeSystem.md'
      - Class Diagrams: 'typesystem/ClassDiagrams.md'
      - Java Integration: 'typesystem/JavaIntegration.md'
      - Primitives: 'typesystem/Primitives.md'
      - Collections: 'typesystem/Collections.md'
  - License: https://monticore.github.io/monticore/00.org/Licenses/LICENSE-MONTICORE-3-LEVEL/
