/* (c) https://github.com/MontiCore/monticore */
package montiarc.timed.composition;

import montiarc.types.OnOff;
import montiarc.maunit.api.AssertEqualsTimed;
import montiarc.maunit.api.EmitTimed;
import java.util.List;

<<test, ticks=[1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],
input1=[
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[]],
  [[]],
  [[OnOff.ON]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], []],
  [[], []],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[], []],
  [[OnOff.ON], [], []],
  [[OnOff.ON], [], []],
  [[OnOff.OFF], [], []],
  [[OnOff.OFF], [], []],
  [[], [OnOff.ON], []],
  [[], [OnOff.ON], []],
  [[], [OnOff.OFF], []],
  [[], [OnOff.OFF], []],
  [[], [], [OnOff.ON]],
  [[], [], [OnOff.ON]],
  [[], [], [OnOff.OFF]],
  [[], [], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]]
], input2=[
  [[]],
  [[]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[], []],
  [[], []],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[], []],
  [[OnOff.ON], [], []],
  [[OnOff.OFF], [], []],
  [[OnOff.ON], [], []],
  [[OnOff.OFF], [], []],
  [[], [OnOff.ON], []],
  [[], [OnOff.OFF], []],
  [[], [OnOff.ON], []],
  [[], [OnOff.OFF], []],
  [[], [], [OnOff.ON]],
  [[], [], [OnOff.OFF]],
  [[], [], [OnOff.ON]],
  [[], [], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF], [OnOff.OFF]]
], expected2=[
  [[]],
  [[]],
  [[OnOff.OFF]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[OnOff.ON]],
  [[OnOff.OFF]],
  [[OnOff.ON]],
  [[], []],
  [[], []],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.ON]],
  [[], [OnOff.OFF]],
  [[], [OnOff.OFF]],
  [[], [OnOff.OFF]],
  [[], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[OnOff.ON], [OnOff.OFF]],
  [[OnOff.ON], [OnOff.ON]],
  [[], []],
  [[OnOff.OFF], [], []],
  [[OnOff.ON], [], []],
  [[OnOff.OFF], [], []],
  [[OnOff.ON], [], []],
  [[], [OnOff.OFF], []],
  [[], [OnOff.ON], []],
  [[], [OnOff.OFF], []],
  [[], [OnOff.ON], []],
  [[], [], [OnOff.OFF]],
  [[], [], [OnOff.ON]],
  [[], [], [OnOff.OFF]],
  [[], [], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.OFF], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.ON]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.OFF]],
  [[OnOff.OFF], [OnOff.ON], [OnOff.ON]]
]>>
component ParallelCompositionTest(List<List<OnOff>> input1, List<List<OnOff>> input2, List<List<OnOff>> expected2) {
  ParallelComposition sut();

  generator1.out -> sut.i1;
  sut.o1 -> assertions1.actual;
  generator2.out -> sut.i2;
  sut.o2 -> assertions2.actual;

  EmitTimed<OnOff> generator1(input1);
  AssertEqualsTimed<OnOff> assertions1(input1);

  EmitTimed<OnOff> generator2(input2);
  AssertEqualsTimed<OnOff> assertions2(expected2);
}
