/* (c) https://github.com/MontiCore/monticore */
package montiarc.timed.composition;

import montiarc.types.OnOff;
import montiarc.maunit.api.AssertEqualsTimed;
import montiarc.maunit.api.EmitTimed;

<<test, ticks=[1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3],
input1=[
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff><Tick>,
  <OnOff><Tick>,
  <OnOff.ON, Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff><Tick, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>
], input2=[
  <OnOff><Tick>,
  <OnOff><Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff><Tick, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>
], expected2=[
  <OnOff><Tick>,
  <OnOff><Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.ON, Tick>,
  <OnOff.OFF, Tick>,
  <OnOff.ON, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff><Tick, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.ON, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff><Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <OnOff.OFF, Tick, Tick, Tick>,
  <OnOff.ON, Tick, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, OnOff.OFF, Tick, Tick>,
  <Tick, OnOff.ON, Tick, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <Tick, Tick, OnOff.OFF, Tick>,
  <Tick, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.OFF, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.ON, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.OFF, Tick>,
  <OnOff.OFF, Tick, OnOff.ON, Tick, OnOff.ON, Tick>
]>>
component ParallelCompositionTest(EventStream<OnOff> input1, EventStream<OnOff> input2, EventStream<OnOff> expected2) {
  ParallelComposition sut();

  generator1.out -> sut.i1;
  sut.o1 -> assertions1.actual;
  generator2.out -> sut.i2;
  sut.o2 -> assertions2.actual;

  EmitTimed<OnOff> generator1(input1);
  AssertEqualsTimed<OnOff> assertions1(input1);

  EmitTimed<OnOff> generator2(input2);
  AssertEqualsTimed<OnOff> assertions2(expected2);
}
