/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package montiarc._symboltable;

public class PortKind implements de.monticore.symboltable.SymbolKind {

  public static final PortKind INSTANCE = new PortKind();

  private static final String NAME = PortKind.class.getName();

  @Override
  public String getName() {
    return NAME;
  }

  protected PortKind() {
  }

}