/* generated from model null*/
/* generated by template symboltable.SymbolKind*/


package montiarc._symboltable;

import de.monticore.symboltable.SymbolKind;

public class StateKind implements SymbolKind {

  public static final StateKind KIND = new StateKind();

  private static final String NAME = StateKind.class.getName();

  @Override
  public String getName() {
    return NAME;
  }

  protected StateKind(){
    
  }

}
