/* generated from model null*/
/* generated by template symboltable.SymbolKind*/


package montiarc._symboltable;

import de.monticore.symboltable.SymbolKind;

public class StateKind implements SymbolKind {

  public static final StateKind KIND = new StateKind();

  protected StateKind(){
    
  }

}
