/* (c) https://github.com/MontiCore/monticore */
/* generated from model null*/
/* generated by template symboltable.Scope*/

package montiarc._symboltable;

import java.util.Optional;

import de.monticore.symboltable.MutableScope;

public class TransitionScope extends de.monticore.symboltable.CommonScope {
  
  public TransitionScope(Optional<MutableScope> enclosingScope) {
    super(enclosingScope, true);
  }
  
  public TransitionScope() {
    super(Optional.empty());
  }
}
