/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package montiarc._symboltable;

import de.monticore.symboltable.SymbolKind;

public class VariableKind implements SymbolKind {
  
  public static final VariableKind INSTANCE = new VariableKind();
  
  protected VariableKind() {
  }
  
}
