/* generated by template templates.de.monticore.lang.montiarc.tagschema.ValuedTagTypeCreator*/


package nfp.PowerConsumptionTagSchema;

import java.util.Collection;
import java.util.Optional;
import java.util.stream.Collectors;

import de.monticore.lang.montiarc.montiarc._symboltable.*;
import de.monticore.lang.montiarc.montiarc._symboltable.ConnectorSymbol;
import de.monticore.lang.montiarc.tagging._ast.ASTNameScope;
import de.monticore.lang.montiarc.tagging._ast.ASTScope;
import de.monticore.lang.montiarc.tagging._ast.ASTTag;
import de.monticore.lang.montiarc.tagging._ast.ASTTaggingUnit;
import de.monticore.lang.montiarc.tagging._symboltable.TagSymbolCreator;
import de.monticore.symboltable.Scope;
import de.monticore.symboltable.Symbol;
import de.monticore.symboltable.SymbolKind;
import de.se_rwth.commons.Joiners;
import de.se_rwth.commons.logging.Log;

import de.monticore.lang.montiarc.tagvalue._parser.TagValueParser;
import de.monticore.lang.montiarc.tagvalue._ast.ASTStringTagValue;

/**
 * created by ValuedTagTypeCreator.ftl
 */
public class PowerTesterSymbolCreator implements TagSymbolCreator {

  public static Scope getGlobalScope(final Scope scope) {
    Scope s = scope;
    while (s.getEnclosingScope().isPresent()) {
      s = s.getEnclosingScope().get();
    }
    return s;
  }

  public void create(ASTTaggingUnit unit, Scope gs) {
    if (unit.getQualifiedNames().stream()
        .map(q -> q.toString())
        .filter(n -> n.endsWith("PowerConsumptionTagSchema"))
        .count() == 0) {
      return; // the tagging model is not conform to the PowerConsumptionTagSchema tagging schema
    }
    final String packageName = Joiners.DOT.join(unit.getPackage());
    final String rootCmp = // if-else does not work b/c of final (required by streams)
        (unit.getTagBody().getTargetModel().isPresent()) ?
            Joiners.DOT.join(packageName,
                unit.getTagBody().getTargetModel().get()
                .getQualifiedNameString()) :
            packageName;

    for (ASTTag element : unit.getTagBody().getTags()) {
      element.getTagElements().stream()
          .filter(t -> t.getName().equals("PowerTester"))
          .filter(t -> t.getTagValue().isPresent())
          .map(t -> checkContent(t.getTagValue().get()))
          .filter(v -> v != null)
          .forEachOrdered(v ->
              element.getScopes().stream()
                .filter(this::checkScope)
                .map(s -> (ASTNameScope) s)
                .map(s -> getGlobalScope(gs).<Symbol>resolveDownMany(
                    Joiners.DOT.join(rootCmp, s.getQualifiedName().toString()),
                    SymbolKind.KIND))
                .filter(s -> !s.isEmpty())
                .map(this::checkKind)
                .filter(s -> s != null)
                .forEachOrdered(s -> s.addTag(new PowerTesterSymbol(v))));
    }
  }

  protected String checkContent(String s) {
    TagValueParser parser = new TagValueParser();
    Optional<ASTStringTagValue> ast;
    try {
      boolean enableFailQuick = Log.isFailQuickEnabled();
      Log.enableFailQuick(false);
      long errorCount = Log.getErrorCount();

      ast = parser.parseString_StringTagValue(s);

      Log.enableFailQuick(enableFailQuick);
      if (Log.getErrorCount() > errorCount) {
        throw new Exception("Error occured during parsing.");
      }
    } catch (Exception e) {
      Log.error(String.format("0xT0004 Could not parse %s with TagValueParser#parseString_StringTagValue.",
          s), e);
      return null;
    }
    if (!ast.isPresent()) {
      return null;
    }
    return ast.get().getString();
  }

  protected PortSymbol checkKind(Collection<Symbol> symbols) {
    PortSymbol ret = null;
    for (Symbol symbol : symbols) {
      if (symbol.getKind().isSame(PortSymbol.KIND)) {
        if (ret != null) {
          Log.error(String.format("0xA4095 Found more than one symbol: '%s' and '%s'",
              ret, symbol));
          return null;
        }
        ret = (PortSymbol)symbol;
      }
    }
    if (ret == null) {
      Log.error(String.format("0xT0001 Invalid symbol kinds: %s. tagTypeName expects as symbol kind 'PortSymbol.KIND'.",
          symbols.stream().map(s -> "'" + s.getKind().toString() + "'").collect(Collectors.joining(", "))));
      return null;
    }
    return ret;
  }

  protected boolean checkScope(ASTScope scope) {
    if (scope.getScopeKind().equals("NameScope")) {
      return true;
    }
    Log.error(String.format("0xT0005 Invalid scope kind: '%s'. PowerTester expects as scope kind 'NameScope'.",
        scope.getScopeKind()), scope.get_SourcePositionStart());
    return false;
  }
}