/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class AutomatonSymbolEMPTY extends de.monticore.symboltable.CommonScopeSpanningSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final AutomatonKind KIND = new AutomatonKind();


  public AutomatonSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
