/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.automaton.ioautomaton._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class AutomatonResolvingFilter extends CommonResolvingFilter<AutomatonSymbol> {

  public AutomatonResolvingFilter() {
    super(AutomatonSymbol.class, AutomatonSymbol.KIND);
  }
}
