/* generated from model null*/
/* generated by template symboltable.Symbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class AutomatonSymbolTOP extends AutomatonSymbolEMPTY {

  public AutomatonSymbolTOP(String name) {
    super(name);
  }

  /* generated by template symboltable.symbols.Attributes*/




  /* generated by template symboltable.symbols.GetterSetter*/





}
