/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.automaton.ioautomaton._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class GuardResolvingFilter extends CommonResolvingFilter<GuardSymbol> {

  public GuardResolvingFilter() {
    super(GuardSymbol.class, GuardSymbol.KIND);
  }
}
