/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class GuardSymbolEMPTY extends de.monticore.symboltable.CommonSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final GuardKind KIND = new GuardKind();


  public GuardSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
