/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class InitialStateDeclarationSymbolEMPTY extends de.monticore.symboltable.CommonSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final InitialStateDeclarationKind KIND = new InitialStateDeclarationKind();


  public InitialStateDeclarationSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
