/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.automaton.ioautomaton._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class InitialStateDeclarationResolvingFilter extends CommonResolvingFilter<InitialStateDeclarationSymbol> {

  public InitialStateDeclarationResolvingFilter() {
    super(InitialStateDeclarationSymbol.class, InitialStateDeclarationSymbol.KIND);
  }
}
