/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class StateSymbolEMPTY extends de.monticore.symboltable.CommonSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final StateKind KIND = new StateKind();


  public StateSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
