/* generated from model null*/
/* generated by template symboltable.ScopeSpanningSymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class TransitionSymbolTOP extends TransitionSymbolEMPTY {

  public TransitionSymbolTOP(String name) {
    super(name);
  }

 /* generated by template symboltable.symbols.Attributes*/




 /* generated by template symboltable.symbols.GetterSetter*/








}
