/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.automaton.ioautomaton._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class TransitionResolvingFilter extends CommonResolvingFilter<TransitionSymbol> {

  public TransitionResolvingFilter() {
    super(TransitionSymbol.class, TransitionSymbol.KIND);
  }
}
