/* generated from model null*/
/* generated by template symboltable.EmptyScopeSpanningSymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

import static de.monticore.symboltable.Symbols.sortSymbolsByPosition;

import java.util.Collection;

public class TransitionSymbolEMPTY extends de.monticore.symboltable.CommonScopeSpanningSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final TransitionKind KIND = new TransitionKind();


  public TransitionSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
