/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.automaton.ioautomaton._symboltable;

public class VariableSymbolEMPTY extends de.monticore.symboltable.CommonSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final VariableKind KIND = new VariableKind();


  public VariableSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
