/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.montiarc.tagging._symboltable;

public class TagKind implements de.monticore.symboltable.SymbolKind {

  public static final TagKind INSTANCE = new TagKind();

  protected TagKind() {
  }

}