/* (c) https://github.com/MontiCore/monticore */
package montiarc.timed.automata.hierarchical.actions;

import montiarc.maunit.api.AssertEqualsTimed;
import montiarc.maunit.api.EmitTimed;

<<test={
  [Event<String><"c", Tick, "ccc -> c", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "c ->", "ccc -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", "ccc -> c", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "c ->", "ccc -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", Tick, "ccc -> cc", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "ccc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", "ccc -> cc", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "ccc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"d", Tick, "ddd -> d", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "d ->", "ddd -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick>],
  [Event<String><"d", "ddd -> d", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "ddd -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick>],
  [Event<String><"d", Tick, "ddd -> dd", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "ddd -> dd", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick>],
  [Event<String><"d", "ddd -> dd", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "ddd -> dd", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick>],
  [Event<String><"f", Tick, "fff -> f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "fff -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff -> f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "fff -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff -> ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> ff", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff -> ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> ff", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_ff -> fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff_ff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_ff -> fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff_ff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_ff -> fff_f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_ff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_ff -> fff_f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_ff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_fff -> fff_f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_fff -> fff_f", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_fff -> fff_ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_fff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_fff -> fff_ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_fff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"b", Tick, "b -> bz", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", Tick, "bb ->", "b ->", "b -> bz", "-> b", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz", Tick>],
  [Event<String><"b", "b -> bz", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "bb ->", "b ->", "b -> bz", "-> b", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz", Tick>],
  [Event<String><"c", Tick, "c -> cz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "c ->", "c -> cz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"c", "c -> cz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "c ->", "c -> cz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"c", Tick, "c -> czz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "c ->", "c -> czz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"c", "c -> czz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "c ->", "c -> czz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"d", Tick, "d -> dz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"d", "d -> dz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"d", Tick, "d -> dzz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dzz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"d", "d -> dzz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dzz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"d", Tick, "dd -> ddz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "dd -> ddz", "-> dd", "-> ddz", "-> ddz_z", "-> ddz_zz", "-> ddz_zzz", "~ d", "~ dd", "~ ddz", "~ ddz_z", "~ ddz_zz", "~ ddz_zzz", Tick>],
  [Event<String><"d", "dd -> ddz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "dd -> ddz", "-> dd", "-> ddz", "-> ddz_z", "-> ddz_zz", "-> ddz_zzz", "~ d", "~ dd", "~ ddz", "~ ddz_z", "~ ddz_zz", "~ ddz_zzz", Tick>],
  [Event<String><"f", Tick, "f -> ffz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> ffz", "-> f", "-> ff", "-> ffz", "-> ffz_z", "-> ffz_zz", "-> ffz_zzz", "~ f", "~ ff", "~ ffz", "~ ffz_z", "~ ffz_zz", "~ ffz_zzz", Tick>],
  [Event<String><"f", "f -> ffz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> ffz", "-> f", "-> ff", "-> ffz", "-> ffz_z", "-> ffz_zz", "-> ffz_zzz", "~ f", "~ ff", "~ ffz", "~ ffz_z", "~ ffz_zz", "~ ffz_zzz", Tick>],
  [Event<String><"f", Tick, "f -> fzz_z", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> fzz_z", "-> f", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz", Tick>],
  [Event<String><"f", "f -> fzz_z", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> fzz_z", "-> f", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz", Tick>],
  [Event<String><"f", Tick, "fff -> fff_zz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"f", "fff -> fff_zz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"f", Tick, "fff -> fff_zzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zzz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"f", "fff -> fff_zzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zzz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"f", Tick, "fff_f -> fff_fz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_f -> fff_fz", "-> fff_f", "-> fff_fz", "-> fff_fzz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_fz", "~ fff_fzz", Tick>],
  [Event<String><"f", "fff_f -> fff_fz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_f -> fff_fz", "-> fff_f", "-> fff_fz", "-> fff_fzz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_fz", "~ fff_fzz", Tick>],
  [Event<String><"b", Tick, "bb -> bz", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", Tick, "bb ->", "bb -> bz", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz", Tick>],
  [Event<String><"b", "bb -> bz", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "bb ->", "bb -> bz", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz", Tick>],
  [Event<String><"c", Tick, "cc -> cz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "cc -> cz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"c", "cc -> cz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "cc -> cz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"d", Tick, "dd -> dz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", Tick, "ddd_d ->", "ddd ->", "dd ->", "dd -> dz", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"d", "dd -> dz", Tick>, Event<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "ddd_d ->", "ddd ->", "dd ->", "dd -> dz", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz", Tick>],
  [Event<String><"e", Tick, "ee -> ez", Tick>, Event<String><"INIT -> e", "-> e", "-> ee", "-> eee", "-> eee_e", "-> eee_ee", "~ e", "~ ee", "~ eee", "~ eee_e", "~ eee_ee", Tick, "eee_ee ->", "eee_e ->", "eee ->", "ee ->", "ee -> ez", "-> ez", "-> ezz", "-> ezz_z", "-> ezz_zz", "-> ezz_zzz", "~ e", "~ ez", "~ ezz", "~ ezz_z", "~ ezz_zz", "~ ezz_zzz", Tick>],
  [Event<String><"e", "ee -> ez", Tick>, Event<String><"INIT -> e", "-> e", "-> ee", "-> eee", "-> eee_e", "-> eee_ee", "eee_ee ->", "eee_e ->", "eee ->", "ee ->", "ee -> ez", "-> ez", "-> ezz", "-> ezz_z", "-> ezz_zz", "-> ezz_zzz", "~ e", "~ ez", "~ ezz", "~ ezz_z", "~ ezz_zz", "~ ezz_zzz", Tick>],
  [Event<String><"c", Tick, "ccc -> ccz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "ccc -> ccz", "-> ccz", "-> ccz_z", "-> ccz_zz", "-> ccz_zzz", "~ c", "~ cc", "~ ccz", "~ ccz_z", "~ ccz_zz", "~ ccz_zzz", Tick>],
  [Event<String><"c", "ccc -> ccz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "ccc -> ccz", "-> ccz", "-> ccz_z", "-> ccz_zz", "-> ccz_zzz", "~ c", "~ cc", "~ ccz", "~ ccz_z", "~ ccz_zz", "~ ccz_zzz", Tick>],
  [Event<String><"c", Tick, "ccc -> czz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "ccc -> czz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"c", "ccc -> czz", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "ccc -> czz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz", Tick>],
  [Event<String><"f", Tick, "fff -> fzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> fzz", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz", Tick>],
  [Event<String><"f", "fff -> fzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> fzz", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz", Tick>],
  [Event<String><"f", Tick, "fff_fff -> fff_ffz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_fff -> fff_ffz", "-> fff_ffz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_ffz", Tick>],
  [Event<String><"f", "fff_fff -> fff_ffz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_fff -> fff_ffz", "-> fff_ffz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_ffz", Tick>],
  [Event<String><"f", Tick, "fff_fff -> fff_zzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_zzz", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"f", "fff_fff -> fff_zzz", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_zzz", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz", Tick>],
  [Event<String><"b", Tick, "b -> b", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", Tick, "bb ->", "b ->", "b -> b", "-> b", "-> bb", "~ b", "~ bb", Tick>],
  [Event<String><"b", "b -> b", Tick>, Event<String><"INIT -> b", "-> b", "-> bb", "bb ->", "b ->", "b -> b", "-> b", "-> bb", "~ b", "~ bb", Tick>],
  [Event<String><"c", Tick, "c -> c", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "c ->", "c -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", "c -> c", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "c ->", "c -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", Tick, "cc -> cc", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick, "ccc ->", "cc ->", "cc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"c", "cc -> cc", Tick>, Event<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "ccc ->", "cc ->", "cc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", Tick>],
  [Event<String><"f", Tick, "fff -> fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff -> fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_ff -> fff_ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_ff ->", "fff_ff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_ff -> fff_ff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_ff ->", "fff_ff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", Tick, "fff_fff -> fff_fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick, "fff_fff ->", "fff_fff -> fff_fff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>],
  [Event<String><"f", "fff_fff -> fff_fff", Tick>, Event<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "fff_fff ->", "fff_fff -> fff_fff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", Tick>]
}, ticks=[2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1]>>
component NestedTransitionsInSameHierarchyTest(EventStream<String> input, EventStream<String> expected) {
  NestedTransitionsInSameHierarchy sut;

  generator.out -> sut.i;
  sut.o -> assertions.actual;

  EmitTimed<String> generator(input);

  AssertEqualsTimed<String> assertions(expected);
}
