# (c) https://github.com/MontiCore/monticore
[libraries]
apache-commons = "org.apache.commons:commons-lang3:3.17.0"
apache-poi = "org.apache.poi:poi:5.4.1"
api-guardian = "org.apiguardian:apiguardian-api:1.1.2"
assertj = "org.assertj:assertj-core:3.27.3"
freemarker = "org.freemarker:freemarker:2.3.34"
format = "com.google.googlejavaformat:google-java-format:1.9" # >1.24.0 requires Java 17, >1.9 requires JVM flags
guava = "com.google.guava:guava:33.4.8-jre"
jackson = "com.fasterxml.jackson.core:jackson-databind:2.19.1"
janino = "org.codehaus.janino:janino:3.1.12"
junit-api = "org.junit.jupiter:junit-jupiter-api:5.13.2"
junit-engine = "org.junit.jupiter:junit-jupiter-engine:5.13.2"
junit-params = "org.junit.jupiter:junit-jupiter-params:5.13.2"
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.13.2"
junit-platform-testkit = "org.junit.platform:junit-platform-testkit:1.13.2"
smt = "org.sosy-lab:java-smt:5.0.1"
mockito = "org.mockito:mockito-core:5.18.0"
mockito-junit = "org.mockito:mockito-junit-jupiter:5.18.0"
z3 = "tools.aqua:z3-turnkey:4.14.1"
jgrapht-core = "org.jgrapht:jgrapht-core:1.5.2"
jgrapht-jgraphx = "org.tinyjee.jgraphx:jgraphx:3.4.1.3"
jgrapht-ext = "org.jgrapht:jgrapht-ext:1.5.2"
mqtt = "org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5"

mc-lsp = "de.monticore.language-server:monticore-language-server-runtime:7.8.0-SNAPSHOT"
mc-grammar = "de.monticore:monticore-grammar:7.8.0-SNAPSHOT"
mc-runtime = "de.monticore:monticore-runtime:7.8.0-SNAPSHOT"
mc-c2mc = "de.monticore:class2mc:7.8.0-SNAPSHOT"
se-logging = "de.se_rwth.commons:se-commons-logging:7.8.0-SNAPSHOT"
se-utilities = "de.se_rwth.commons:se-commons-utilities:7.8.0-SNAPSHOT"
mc-cd4a = "de.monticore.lang:cd4analysis:7.8.0-SNAPSHOT"
mc-ocl = "de.monticore.lang:ocl:7.8.0-SNAPSHOT"
mc-ocl-ocl2smt = "de.monticore.lang.ocl:ocl2smt:7.8.0-SNAPSHOT"
mc-sc = "de.monticore.lang:statecharts:7.8.0-SNAPSHOT"
mc-fd = "de.monticore.lang:fd-lang:7.8.0-SNAPSHOT"

shadow = "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.18.0"
kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.21"
se-commons = "de.se_rwth.commons:se-commons-gradle:7.8.0-SNAPSHOT"
mc-generator = "de.monticore.generator:de.monticore.generator.gradle.plugin:7.8.0-SNAPSHOT"
mc-language-server = "de.monticore.language-server:de.monticore.language-server.gradle.plugin:7.8.0-SNAPSHOT"
node-gradle = "com.github.node-gradle:gradle-node-plugin:5.0.0"

[plugins]
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" } # >0.51.0 requires Kotlin 2.x
