# (c) https://github.com/MontiCore/monticore
[libraries]
apache-commons = "org.apache.commons:commons-lang3:3.20.0"
apache-poi = "org.apache.poi:poi:5.5.1"
api-guardian = "org.apiguardian:apiguardian-api:1.1.2"
assertj = "org.assertj:assertj-core:3.27.7"
freemarker = "org.freemarker:freemarker:2.3.34"
format = "org.eclipse.jdt:org.eclipse.jdt.core:3.46.0"
guava = "com.google.guava:guava:33.7.0-jre"
jackson = "tools.jackson.core:jackson-databind:3.2.2"
janino = "org.codehaus.janino:janino:3.1.12"
junit-api = "org.junit.jupiter:junit-jupiter-api:6.1.3"
junit-engine = "org.junit.jupiter:junit-jupiter-engine:6.1.3"
junit-params = "org.junit.jupiter:junit-jupiter-params:6.1.3"
junit-pioneer = "org.junit-pioneer:junit-pioneer:2.3.0"
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:6.1.3"
junit-platform-testkit = "org.junit.platform:junit-platform-testkit:6.1.3"
smt = "org.sosy-lab:java-smt:5.0.1" # >=6.0.0 has breaking changes
mockito = "org.mockito:mockito-core:5.23.0"
mockito-junit = "org.mockito:mockito-junit-jupiter:5.23.0"
z3 = "tools.aqua:z3-turnkey:4.14.1"
jgrapht-core = "org.jgrapht:jgrapht-core:1.5.3"
jgrapht-jgraphx = "org.tinyjee.jgraphx:jgraphx:3.4.1.3"
jgrapht-ext = "org.jgrapht:jgrapht-ext:1.5.3"
mqtt = "org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5"
commons-cli = "commons-cli:commons-cli:1.11.0"
gradle-tooling-api = "org.gradle:gradle-tooling-api:7.3-20210825160000+0000"
fmi4j = "io.github.generosolombardi-av.fmi4j:fmi-import:0.38.0-multiplatform.6"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.18" # required by fmi4j which uses an old log4j version
kotlin-stdlib = "org.jetbrains.kotlin:kotlin-stdlib:2.4.10"

shadow = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:8.3.6"
spotless = "com.diffplug.spotless:spotless-plugin-gradle:8.1.0"
kotlin-gradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21"
node-gradle = "com.github.node-gradle:gradle-node-plugin:5.0.0"
intellij = "org.jetbrains.intellij.platform:org.jetbrains.intellij.platform.gradle.plugin:2.6.0"

[plugins]
versions = { id = "io.github.ben-manes.versions", version = "0.61.0" }
