/* generated from model null*/
/* generated by template symboltable.SymbolKind*/


package de.monticore.lang.montiarc.montiarc._symboltable;

import de.monticore.symboltable.SymbolKind;

public class AutomatonKind implements SymbolKind {

  public static final AutomatonKind KIND = new AutomatonKind();


  @Override
  public boolean isKindOf(SymbolKind kind) {
    return KIND.equals(kind.getName()) || SymbolKind.super.isKindOf(kind);
  }

}
