/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.montiarc.montiarc._symboltable;

public class ConnectorKind implements de.monticore.symboltable.SymbolKind {

  public static final ConnectorKind INSTANCE = new ConnectorKind();

  protected ConnectorKind() {
  }

}