/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.montiarc.montiarc._symboltable;

public class ExpandedComponentInstanceKind
    implements de.monticore.symboltable.SymbolKind {

  public static final ExpandedComponentInstanceKind INSTANCE = new ExpandedComponentInstanceKind();

  protected ExpandedComponentInstanceKind() {
  }

}