/* generated from model null*/
/* generated by template symboltable.SymbolKind*/

package de.monticore.lang.montiarc.montiarc._symboltable;

public class PortKind implements de.monticore.symboltable.SymbolKind {

  public static final PortKind INSTANCE = new PortKind();

  protected PortKind() {
  }

}