/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.lang.montiarc.montiarc._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class StateResolvingFilter extends CommonResolvingFilter<StateSymbol> {

  public StateResolvingFilter() {
    super(StateSymbol.class, StateSymbol.KIND);
  }
}
