/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.lang.montiarc.montiarc._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class VariableResolvingFilter extends CommonResolvingFilter<VariableSymbol> {

  public VariableResolvingFilter() {
    super(VariableSymbol.class, VariableSymbol.KIND);
  }
}
