/* (c) https://github.com/MontiCore/monticore */
package montiarc.sync.automata.hierarchical.actions;

import montiarc.maunit.api.AssertEqualsUntimed;
import montiarc.maunit.api.EmitSync;

<<test={
  [Sync<String><"c", "ccc -> c">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "c ->", "ccc -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc">],
  [Sync<String><"c", "ccc -> cc">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "ccc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc">],
  [Sync<String><"d", "ddd -> d">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "ddd -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d">],
  [Sync<String><"d", "ddd -> dd">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "ddd -> dd", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d">],
  [Sync<String><"f", "fff -> f">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "fff -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff -> ff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> ff", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_ff -> fff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff_ff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_ff -> fff_f">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_ff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_fff -> fff_f">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_f", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_fff -> fff_ff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_fff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"b", "b -> bz">, Untimed<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", "bb ->", "b ->", "b -> bz", "-> b", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz">],
  [Sync<String><"c", "c -> cz">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "c ->", "c -> cz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz">],
  [Sync<String><"c", "c -> czz">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "c ->", "c -> czz", "-> c", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz">],
  [Sync<String><"d", "d -> dz">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz">],
  [Sync<String><"d", "d -> dzz">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "d ->", "d -> dzz", "-> d", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz">],
  [Sync<String><"d", "dd -> ddz">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "dd -> ddz", "-> dd", "-> ddz", "-> ddz_z", "-> ddz_zz", "-> ddz_zzz", "~ d", "~ dd", "~ ddz", "~ ddz_z", "~ ddz_zz", "~ ddz_zzz">],
  [Sync<String><"f", "f -> ffz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> ffz", "-> f", "-> ff", "-> ffz", "-> ffz_z", "-> ffz_zz", "-> ffz_zzz", "~ f", "~ ff", "~ ffz", "~ ffz_z", "~ ffz_zz", "~ ffz_zzz">],
  [Sync<String><"f", "f -> fzz_z">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "f ->", "f -> fzz_z", "-> f", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz">],
  [Sync<String><"f", "fff -> fff_zz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz">],
  [Sync<String><"f", "fff -> fff_zzz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff_zzz", "-> fff", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz">],
  [Sync<String><"f", "fff_f -> fff_fz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_f -> fff_fz", "-> fff_f", "-> fff_fz", "-> fff_fzz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_fz", "~ fff_fzz">],
  [Sync<String><"b", "bb -> bz">, Untimed<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", "bb ->", "bb -> bz", "-> bz", "-> bzz", "-> bzz_z", "-> bzz_zz", "-> bzz_zzz", "~ b", "~ bz", "~ bzz", "~ bzz_z", "~ bzz_zz", "~ bzz_zzz">],
  [Sync<String><"c", "cc -> cz">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "cc -> cz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz">],
  [Sync<String><"d", "dd -> dz">, Untimed<String><"INIT -> d", "-> d", "-> dd", "-> ddd", "-> ddd_d", "~ d", "~ dd", "~ ddd", "~ ddd_d", "ddd_d ->", "ddd ->", "dd ->", "dd -> dz", "-> dz", "-> dzz", "-> dzz_z", "-> dzz_zz", "-> dzz_zzz", "~ d", "~ dz", "~ dzz", "~ dzz_z", "~ dzz_zz", "~ dzz_zzz">],
  [Sync<String><"e", "ee -> ez">, Untimed<String><"INIT -> e", "-> e", "-> ee", "-> eee", "-> eee_e", "-> eee_ee", "~ e", "~ ee", "~ eee", "~ eee_e", "~ eee_ee", "eee_ee ->", "eee_e ->", "eee ->", "ee ->", "ee -> ez", "-> ez", "-> ezz", "-> ezz_z", "-> ezz_zz", "-> ezz_zzz", "~ e", "~ ez", "~ ezz", "~ ezz_z", "~ ezz_zz", "~ ezz_zzz">],
  [Sync<String><"c", "ccc -> ccz">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "ccc -> ccz", "-> ccz", "-> ccz_z", "-> ccz_zz", "-> ccz_zzz", "~ c", "~ cc", "~ ccz", "~ ccz_z", "~ ccz_zz", "~ ccz_zzz">],
  [Sync<String><"c", "ccc -> czz">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "ccc -> czz", "-> cz", "-> czz", "-> czz_z", "-> czz_zz", "-> czz_zzz", "~ c", "~ cz", "~ czz", "~ czz_z", "~ czz_zz", "~ czz_zzz">],
  [Sync<String><"f", "fff -> fzz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "ff ->", "fff -> fzz", "-> fz", "-> fzz", "-> fzz_z", "-> fzz_zz", "-> fzz_zzz", "~ f", "~ fz", "~ fzz", "~ fzz_z", "~ fzz_zz", "~ fzz_zzz">],
  [Sync<String><"f", "fff_fff -> fff_ffz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_fff -> fff_ffz", "-> fff_ffz", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_ffz">],
  [Sync<String><"f", "fff_fff -> fff_zzz">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff_fff -> fff_zzz", "-> fff_z", "-> fff_zz", "-> fff_zzz", "~ f", "~ ff", "~ fff", "~ fff_z", "~ fff_zz", "~ fff_zzz">],
  [Sync<String><"b", "b -> b">, Untimed<String><"INIT -> b", "-> b", "-> bb", "~ b", "~ bb", "bb ->", "b ->", "b -> b", "-> b", "-> bb", "~ b", "~ bb">],
  [Sync<String><"c", "c -> c">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "c ->", "c -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc">],
  [Sync<String><"c", "cc -> cc">, Untimed<String><"INIT -> c", "-> c", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc", "ccc ->", "cc ->", "cc -> cc", "-> cc", "-> ccc", "~ c", "~ cc", "~ ccc">],
  [Sync<String><"f", "fff -> fff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_f ->", "fff ->", "fff -> fff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_ff -> fff_ff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_ff ->", "fff_ff -> fff_ff", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">],
  [Sync<String><"f", "fff_fff -> fff_fff">, Untimed<String><"INIT -> f", "-> f", "-> ff", "-> fff", "-> fff_f", "-> fff_ff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff", "fff_fff ->", "fff_fff -> fff_fff", "-> fff_fff", "~ f", "~ ff", "~ fff", "~ fff_f", "~ fff_ff", "~ fff_fff">]
}, ticks=[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]>>
component NestedTransitionsInSameHierarchyTest(SyncStream<String> input, UntimedStream<String> expected) {
  NestedTransitionsInSameHierarchy sut;

  generator.out -> sut.i;
  sut.o -> assertions.actual;

  EmitSync<String> generator(input);

  AssertEqualsUntimed<String> assertions(expected);
}
