/* (c) https://github.com/MontiCore/monticore */
/* generated from model MontiArc*/
/* generated by template ast.AstClass*/

package montiarc._ast;

import java.util.Optional;

public class ASTGuard extends ASTGuardTOP {
  
  /**
   * Constructor for montiarc._ast.ASTGuard
   * 
   * @param kind
   * @param guardExpression
   */
  public ASTGuard(ASTGuardExpression guardExpression) {
    super(guardExpression);
  }
  
  public ASTGuard() {
    super();
  }
  
  public String getName() {
    String syntheticName = "[Guard] @ " + this.get_SourcePositionStart();
    return syntheticName;
  }
  
}
