/* generated from model MontiArc*/
/* generated by template ast.AstClass*/

package montiarc._ast;

import java.util.List;
import java.util.Optional;

import de.se_rwth.commons.Names;

public class ASTInitialStateDeclaration extends ASTInitialStateDeclarationTOP {
  
  public ASTInitialStateDeclaration() {
    super();
  }
  
  /**
   * Constructor for montiarc._ast.ASTInitialStateDeclaration
   * 
   * @param names
   * @param block
   */
  protected ASTInitialStateDeclaration(List<String> names, Optional<ASTBlock> block) {
    super(names, block);
  }
  
  public String getName() {
    return Names.getQualifiedName(getNameList());
  }
  
}
