/* generated from model MontiArc*/
/* generated by template ast.AstClass*/

package montiarc._ast;

public class ASTTransition extends ASTTransitionTOP {
  
  public ASTTransition() {
    super();
  }
  
  public ASTTransition(
      String source,
      String target,
      ASTGuard guard,
      ASTBlock stimulus,
      ASTBlock reaction) {
    super(source,target,guard,stimulus,reaction);
  }

  public String getName() {
    String syntheticName = this.getSource() + "-" + this.getTarget() + "@" + this.get_SourcePositionStart(); 
    return syntheticName;
  }
  
}