/* (c) https://github.com/MontiCore/monticore */
/* generated from model MontiArc*/
/* generated by template ast.AstClass*/

package montiarc._ast;

import java.util.Optional;

public class ASTTransition extends ASTTransitionTOP {
  
  /**
   * Constructor for montiarc._ast.ASTTransition
   */
  protected ASTTransition() {
    super();
  }

  /**
   * Constructor for montiarc._ast.ASTTransition
   * @param source
   * @param target
   * @param guard
   * @param stimulus
   * @param reaction
   */
  protected ASTTransition(
      String source,
      Optional<String> target,
      Optional<ASTGuard> guard,
      Optional<ASTBlock> reaction) {
    super(source, target, guard, reaction);
  }

  public String getName() {
    String syntheticName = this.getSource() + "-" + this.getTarget() + "@"
        + this.get_SourcePositionStart();
    return syntheticName;
  }
  
}
