/* generated by template templates.de.monticore.lang.montiarc.tagschema.TagSchema*/


package de.monticore.lang.montiarc.tag.drawing.TraceabilityTagSchema;

import de.monticore.CommonModelingLanguage;
import de.monticore.lang.montiarc.tagging._symboltable.TagableModelingLanguage;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class TraceabilityTagSchema {

  protected static TraceabilityTagSchema instance = null;

  protected TraceabilityTagSchema() {}

  protected static TraceabilityTagSchema getInstance() {
    if (instance == null) {
      instance = new TraceabilityTagSchema();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TagableModelingLanguage modelingLanguage) {
    // all ModelingLanguage instances are actually instances of CommonModelingLanguage
    if(modelingLanguage instanceof CommonModelingLanguage) {
      CommonModelingLanguage commonModelingLanguage = (CommonModelingLanguage)modelingLanguage;

      modelingLanguage.addTagSymbolCreator(new IsTraceableSymbolCreator());
      commonModelingLanguage.addResolver(CommonResolvingFilter.create(IsTraceableSymbol.KIND));
      modelingLanguage.addTagSymbolCreator(new TraceableSymbolCreator());
      commonModelingLanguage.addResolver(CommonResolvingFilter.create(TraceableSymbol.KIND));
    }
  }

  public static void registerTagTypes(TagableModelingLanguage modelingLanguage) {
    getInstance().doRegisterTagTypes(modelingLanguage);
  }
}