/* generated from model null*/
/* generated by template symboltable.EmptySymbol*/



package de.monticore.lang.montiarc.montiarcautomaton._symboltable;

public class BehaviorEmbeddingSymbolEMPTY extends de.monticore.symboltable.CommonSymbol {

  /* generated by template symboltable.symbols.KindConstantDeclaration*/


  public static final BehaviorEmbeddingKind KIND = new BehaviorEmbeddingKind();


  public BehaviorEmbeddingSymbolEMPTY(String name) {
    super(name, KIND);
  }

}
