/* generated from model null*/
/* generated by template symboltable.ResolvingFilter*/




package de.monticore.lang.montiarc.montiarcautomaton._symboltable;

import de.monticore.symboltable.resolving.CommonResolvingFilter;

public class BehaviorEmbeddingResolvingFilter extends CommonResolvingFilter<BehaviorEmbeddingSymbol> {

  public BehaviorEmbeddingResolvingFilter() {
    super(BehaviorEmbeddingSymbol.class, BehaviorEmbeddingSymbol.KIND);
  }
}
