/* generated from model null*/
/* generated by template symboltable.SymbolKind*/


package de.monticore.lang.montiarc.montiarcautomaton._symboltable;

import de.monticore.symboltable.SymbolKind;

public class BehaviorEmbeddingKind implements SymbolKind {

  private static final String NAME = "de.monticore.lang.montiarc.montiarcautomaton._symboltable.BehaviorEmbeddingKind";

  @Override
  public String getName() {
    return NAME;
  }

  @Override
  public boolean isKindOf(SymbolKind kind) {
    return NAME.equals(kind.getName()) || SymbolKind.super.isKindOf(kind);
  }

}
