/* generated from model null*/
/* generated by template symboltable.Symbol*/



package de.monticore.lang.montiarc.montiarcautomaton._symboltable;

public class BehaviorEmbeddingSymbolTOP extends BehaviorEmbeddingSymbolEMPTY {

  public BehaviorEmbeddingSymbolTOP(String name) {
    super(name);
  }

  /* generated by template symboltable.symbols.Attributes*/




  /* generated by template symboltable.symbols.GetterSetter*/





}
