/* (c) https://github.com/MontiCore/monticore */
package de.monticore.rte.tuples;

import java.util.*;

public class Tuple2<T0, T1> {

  /* Hookpoint: ClassContent:Elements */

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T0 e0
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T1 e1
    /* generated by template cd2java.Value*/;


  /* generated by template cd2java.Constructor*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: ConstructorContent:Annotations */
  protected Tuple2(T0 e0, T1 e1) {
    /* generated by template tuples.Constructor*/

    this.e0 = e0;
    this.e1 = e1;

  }


  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T0 get0() {
    /* generated by template tuples.Getter*/

    return e0;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T1 get1() {
    /* generated by template tuples.Getter*/

    return e1;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public String toString() {
    /* generated by template tuples.ToString*/

    StringBuilder res = new StringBuilder();
    res.append("(");
    res.append(get0().toString());
    res.append(", ");
    res.append(get1().toString());

    res.append(")");
    return res.toString();
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public boolean equals(Object object) {
    /* generated by template tuples.Equals*/

    if (!(object instanceof Tuple2)) {
      return false;
    }
    Tuple2<?, ?> tuple = (Tuple2<?, ?>) object;
    if (!Objects.equals(this.get0(), tuple.get0())) {
      return false;
    }
    if (!Objects.equals(this.get1(), tuple.get1())) {
      return false;
    }
    return true;
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public int hashCode() {
    /* generated by template tuples.HashCode*/

    int result = 1;
    result = 31 * result
      + (this.get0() != null
      ? this.get0().hashCode()
      : 0);
    result = 31 * result
      + (this.get1() != null
      ? this.get1().hashCode()
      : 0);
    return result;
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public static <T0, T1> Tuple2<T0, T1> of(T0 e0, T1 e1) {
    /* generated by template tuples.Of*/

    return new Tuple2<>(
      e0
      ,
      e1

    );

  }

}
