/* (c) https://github.com/MontiCore/monticore */
package de.monticore.rte.tuples;

import java.util.*;

public class Tuple7<T0, T1, T2, T3, T4, T5, T6> {

  /* Hookpoint: ClassContent:Elements */

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T0 e0
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T1 e1
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T2 e2
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T3 e3
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T4 e4
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T5 e5
    /* generated by template cd2java.Value*/;

  /* generated by template cd2java.Attribute*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: AttributeContent:Annotations */
  protected final T6 e6
    /* generated by template cd2java.Value*/;


  /* generated by template cd2java.Constructor*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: ConstructorContent:Annotations */
  protected Tuple7(T0 e0, T1 e1, T2 e2, T3 e3, T4 e4, T5 e5, T6 e6) {
    /* generated by template tuples.Constructor*/

    this.e0 = e0;
    this.e1 = e1;
    this.e2 = e2;
    this.e3 = e3;
    this.e4 = e4;
    this.e5 = e5;
    this.e6 = e6;

  }


  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T0 get0() {
    /* generated by template tuples.Getter*/

    return e0;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T1 get1() {
    /* generated by template tuples.Getter*/

    return e1;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T2 get2() {
    /* generated by template tuples.Getter*/

    return e2;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T3 get3() {
    /* generated by template tuples.Getter*/

    return e3;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T4 get4() {
    /* generated by template tuples.Getter*/

    return e4;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T5 get5() {
    /* generated by template tuples.Getter*/

    return e5;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public T6 get6() {
    /* generated by template tuples.Getter*/

    return e6;

  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public String toString() {
    /* generated by template tuples.ToString*/

    StringBuilder res = new StringBuilder();
    res.append("(");
    res.append(get0().toString());
    res.append(", ");
    res.append(get1().toString());
    res.append(", ");
    res.append(get2().toString());
    res.append(", ");
    res.append(get3().toString());
    res.append(", ");
    res.append(get4().toString());
    res.append(", ");
    res.append(get5().toString());
    res.append(", ");
    res.append(get6().toString());

    res.append(")");
    return res.toString();
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public boolean equals(Object object) {
    /* generated by template tuples.Equals*/

    if (!(object instanceof Tuple7)) {
      return false;
    }
    Tuple7<?, ?, ?, ?, ?, ?, ?> tuple = (Tuple7<?, ?, ?, ?, ?, ?, ?>) object;
    if (!Objects.equals(this.get0(), tuple.get0())) {
      return false;
    }
    if (!Objects.equals(this.get1(), tuple.get1())) {
      return false;
    }
    if (!Objects.equals(this.get2(), tuple.get2())) {
      return false;
    }
    if (!Objects.equals(this.get3(), tuple.get3())) {
      return false;
    }
    if (!Objects.equals(this.get4(), tuple.get4())) {
      return false;
    }
    if (!Objects.equals(this.get5(), tuple.get5())) {
      return false;
    }
    if (!Objects.equals(this.get6(), tuple.get6())) {
      return false;
    }
    return true;
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  @Override
  /* Hookpoint: MethodContent:Annotations */
  public int hashCode() {
    /* generated by template tuples.HashCode*/

    int result = 1;
    result = 31 * result
      + (this.get0() != null
      ? this.get0().hashCode()
      : 0);
    result = 31 * result
      + (this.get1() != null
      ? this.get1().hashCode()
      : 0);
    result = 31 * result
      + (this.get2() != null
      ? this.get2().hashCode()
      : 0);
    result = 31 * result
      + (this.get3() != null
      ? this.get3().hashCode()
      : 0);
    result = 31 * result
      + (this.get4() != null
      ? this.get4().hashCode()
      : 0);
    result = 31 * result
      + (this.get5() != null
      ? this.get5().hashCode()
      : 0);
    result = 31 * result
      + (this.get6() != null
      ? this.get6().hashCode()
      : 0);
    return result;
  }

  /* generated by template cd2java.Method*/
  /* generated by template cd2java.JavaDoc*/

  /* generated by template cd2java.Annotations*/

  /* Hookpoint: MethodContent:Annotations */
  public static <T0, T1, T2, T3, T4, T5, T6> Tuple7<T0, T1, T2, T3, T4, T5, T6> of(T0 e0, T1 e1, T2 e2, T3 e3, T4 e4, T5 e5, T6 e6) {
    /* generated by template tuples.Of*/

    return new Tuple7<>(
      e0
      ,
      e1
      ,
      e2
      ,
      e3
      ,
      e4
      ,
      e5
      ,
      e6

    );

  }

}


