/* (c) https://github.com/MontiCore/monticore */
import montiarc.gradle.ma2jsim.MontiArcCompile
import montiarc.gradle.ma2jsim.compileMontiArcTaskName

/**
 * This build is mostly a test specification. It defines configurations for different compileMontiarc tasks
 * and also defines a task that checks that the correct .java files are generated by them.
 */

plugins {
  id("montiarc.build.jvm")
  id("montiarc.build.repositories")
  id("montiarc.build.project-version")

  id("java")
  id("montiarc-jsim")
}

group = "montiarc.tooling.ma2jsim-plugin-itest"

// Testing correct behavior in the case of fully altered configuration values
val alteredConfigValuesSrcSet = sourceSets.create("alteringAndUsingConfigValues") {
  montiarc.setSrcDirs(listOf("$projectDir/src/${this.name}/alteredMontiarc"))
  montiarc.destinationDirectory.set(layout.buildDirectory.dir("montiarc-for-altered-destination"))
}

tasks.named<MontiArcCompile>(alteredConfigValuesSrcSet.compileMontiArcTaskName) {
  val srcSet = alteredConfigValuesSrcSet
  hwcPath.setFrom("$projectDir/src/${srcSet.name}/alteredJavaHwc")
  symbolpath.setFrom("$projectDir/src/${srcSet.name}/alteredSymbolsDir")
  useClass2Mc.set(true)
}

val alteredConfigCheck = tasks.register("checkAlteringConfigValues", CheckFilesArePresent::class.java) {
  dependsOn(tasks.named(alteredConfigValuesSrcSet.compileMontiArcTaskName))
  group = "verification"

  val expectedGenDir = layout.buildDirectory.dir("montiarc-for-altered-destination")
  val expectedJavaGenDir = expectedGenDir.map { it.dir("java") }
  val expectedSymbolGenDir = expectedGenDir.map { it.dir("symbols") }

  mandatoryFiles.from(
    expectedJavaGenDir.map { it.file("mainpackage/HwcComponentCompImplTOP.java") },
    expectedJavaGenDir.map { it.file("mainpackage/UsingImportedSymbolsComp.java") },
    expectedSymbolGenDir.map { it.file("mainpackage/HwcComponent.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/UsingImportedSymbols.arcsym") }
  )
}
tasks.check.configure { dependsOn(alteredConfigCheck) }



// Testing correct behavior if we provide multiple paths where possible
val multiplePathsSrcSet = sourceSets.create("usingMultiplePathsAsConfigValues") {
  montiarc.setSrcDirs(listOf(
    "$projectDir/src/${this.name}/montiarc",
    "$projectDir/src/${this.name}/montiarc2",
  ))
}

tasks.named<MontiArcCompile>(multiplePathsSrcSet.compileMontiArcTaskName) {
  val srcSet = multiplePathsSrcSet
  hwcPath.setFrom(
    "$projectDir/src/${srcSet.name}/java",
    "$projectDir/src/${srcSet.name}/java2",
  )
  symbolpath.setFrom(
    "$projectDir/src/${srcSet.name}/symbols",
    "$projectDir/src/${srcSet.name}/symbols2",
  )
}

val multiplePathsCheck = tasks.register("checkMultiplePaths", CheckFilesArePresent::class.java) {
  dependsOn(tasks.named(multiplePathsSrcSet.compileMontiArcTaskName))
  group = "verification"

  val expectedGenDir = layout.buildDirectory.dir("montiarc/${multiplePathsSrcSet.name}")
  val expectedJavaGenDir = expectedGenDir.map { it.dir("java") }
  val expectedSymbolGenDir = expectedGenDir.map { it.dir("symbols") }

  mandatoryFiles.from(
    expectedJavaGenDir.map { it.file("mainpackage/HwcComponentCompImplTOP.java") },
    expectedJavaGenDir.map { it.file("mainpackage/HwcComponent2CompTOP.java") },
    expectedJavaGenDir.map { it.file("mainpackage/UsingComponentFromOtherModelPathComp.java") },
    expectedJavaGenDir.map { it.file("mainpackage/UsingImportedSymbolsComp.java") },
    expectedJavaGenDir.map { it.file("mainpackage/ComponentFromModelPath2Comp.java") },
    expectedSymbolGenDir.map { it.file("mainpackage/HwcComponent.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/HwcComponent2.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/UsingComponentFromOtherModelPath.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/UsingImportedSymbols.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/ComponentFromModelPath2.arcsym") }
  )
}
tasks.check.configure { dependsOn(multiplePathsCheck) }



// Testing correct behavior if we provide multiple paths where possible, some existing, some not,
val mixedPathsExistanceSrcSet = sourceSets.create("usingMultiplePathsMixedExistanceAsConfigValues") {
  montiarc.setSrcDirs(listOf(
    "$projectDir/src/${this.name}/montiarc",
    "$projectDir/src/${this.name}/montiarcNotExisting",
  ))
}

tasks.named<MontiArcCompile>(mixedPathsExistanceSrcSet.compileMontiArcTaskName) {
  val srcSet = mixedPathsExistanceSrcSet
  hwcPath.setFrom(
    "$projectDir/src/${srcSet.name}/java",
    "$projectDir/src/${srcSet.name}/javaNotExisting",
  )
  symbolpath.setFrom(
    "$projectDir/src/${srcSet.name}/symbols",
    "$projectDir/src/${srcSet.name}/symbolsNotExisting",
  )
}

val mixedPathExistenceCheck = tasks.register("checkMultipleMixedPathExistence", CheckFilesArePresent::class.java) {
  dependsOn(tasks.named(mixedPathsExistanceSrcSet.compileMontiArcTaskName))
  group = "verification"

  val expectedGenDir = layout.buildDirectory.dir("montiarc/${mixedPathsExistanceSrcSet.name}")
  val expectedJavaGenDir = expectedGenDir.map { it.dir("java") }
  val expectedSymbolGenDir = expectedGenDir.map { it.dir("symbols") }

  mandatoryFiles.from(
    expectedJavaGenDir.map { it.file("mainpackage/HwcComponentCompImplTOP.java") },
    expectedJavaGenDir.map { it.file("mainpackage/UsingImportedSymbolsComp.java") },
    expectedSymbolGenDir.map { it.file("mainpackage/HwcComponent.arcsym") },
    expectedSymbolGenDir.map { it.file("mainpackage/UsingImportedSymbols.arcsym") }
  )
}
tasks.check.configure { dependsOn(mixedPathExistenceCheck) }


/*
// Testing correct behavior if we fully remove configuration values where possible
// For this source set, we do not remove the model path directory, as it would lead to "NO_SOURCE", disabling testing
val removingSrcSet = sourceSets.create("removingDefaultValues")
tasks.named<MontiarcCompile>(removingSrcSet.getCompileMontiarcTaskName()) {
  hwcPath.setFrom()
  symbolpath.setFrom()
}

val removingDefaultValuesCheck = tasks.register("checkRemovingDefaultValues", CheckFilesArePresent::class.java) {
  dependsOn(tasks.named(removingSrcSet.getCompileMontiarcTaskName()))
  group = "verification"

  val expectedGenDir = layout.buildDirectory.dir("montiarc/${removingSrcSet.name}")
  val expectedJavaGenDir = expectedGenDir.map { it.dir("java") }
  val expectedSymbolGenDir = expectedGenDir.map { it.dir("symbols") }

  mandatoryFiles.from(
    expectedJavaGenDir.map { it.file("mainpackage/NoHwcComponent.java") },
    expectedSymbolGenDir.map { it.file("mainpackage/NoHwcComponent.arcsym") }
  )
}
tasks.check.configure { dependsOn(removingDefaultValuesCheck) }
*/


// Testing correct behavior if we change configuration values to unused or absent paths where possible
// For this source set, declaring only an unused model path directory would lead to "NO_SOURCE", disabling testing
val unusedConfigValuesSrcSet = sourceSets.create("declaringUnusedConfigValues")
tasks.named<MontiArcCompile>(unusedConfigValuesSrcSet.compileMontiArcTaskName) {
  val srcSet = unusedConfigValuesSrcSet
  hwcPath.setFrom(file("$projectDir/src/${srcSet.name}/unusedJava"))
  symbolpath.setFrom(file("$projectDir/src/${srcSet.name}/unusedSymbols"))
}

val unusedConfigValuesCheck = tasks.register("checkUnusedConfigValues", CheckFilesArePresent::class.java) {
  dependsOn(tasks.named(unusedConfigValuesSrcSet.compileMontiArcTaskName))
  group = "verification"

  val expectedGenDir = layout.buildDirectory.dir("montiarc/${unusedConfigValuesSrcSet.name}")
  val expectedJavaGenDir = expectedGenDir.map { it.dir("java") }
  val expectedSymbolGenDir = expectedGenDir.map { it.dir("symbols") }

  mandatoryFiles.from(
    expectedJavaGenDir.map { it.file("mainpackage/NoHwcComponentComp.java") },
    expectedSymbolGenDir.map { it.file("mainpackage/NoHwcComponent.arcsym") }
  )
}
tasks.check.configure { dependsOn(unusedConfigValuesCheck) }

tasks.getByName<Test>("test") {
  this.enabled = false
}

abstract class CheckFilesArePresent : DefaultTask() {

  @get:InputFiles
  abstract val mandatoryFiles: ConfigurableFileCollection

  @TaskAction
  fun execute() {
    val absentFiles = mandatoryFiles.files.filter { !it.exists() }
    if (absentFiles.isNotEmpty()) {
      val errorMsg = absentFiles.joinToString(separator = "\n") { "Missing expected file: ${it.path}" }

      throw VerificationException(errorMsg)
    }
  }
}

