/* (c) https://github.com/MontiCore/monticore */
package arcbasis._symboltable;

public class ComponentTypeSymbolSurrogateBuilder extends ComponentTypeSymbolSurrogateBuilderTOP {

  @Override
  public ComponentTypeSymbolSurrogate build ()

  {
    /* generated by template _symboltable.symbolsurrogate.BuildSymbolSurrogate*/

    ComponentTypeSymbolSurrogate symbolReference = new ComponentTypeSymbolSurrogate(name);
    symbolReference.setEnclosingScope(enclosingScope);
    if (this.parent.isPresent()) {
      symbolReference.setParent(this.parent.get());
    } else {
      // Do nothing. Calling .setParentAbsent would try to resolve the surrogate
      // Which we do not necessarily want here. This is also the reason why we
      // use TOP, as the generated code malfunctions here.
    }
    return symbolReference;
  }
}
